### ISSUE TITLE
Convert Archub to be TMF compatible

### ISSUE THREAD

**Issue by Freddo3000** [ARCOMM/ARCOMM#2]
do it

**Comment by BorderKeeper** [comment]
We will use https://github.com/SzwedzikPL/PBOMission to extract the PBO and process the mission.sqm.
Here is an extracted example of AirfieldDay from McPedro: https://pastebin.com/CnkvWpmb

**Comment by Freddo3000** [comment]
This is also an option: https://github.com/headswe/SwiftMissionDeRap
