### ISSUE TITLE
Improve PBOMission so it can parse TMF attributes

### ISSUE THREAD

**Issue by BorderKeeper** [ARCOMM/ARCOMM#5]
Will need to be tweaked to start including 
GLOBAL:
TMF_ORBATSettings for ORBAT stuff (optional)
TMF_AcreSettings for radios
TMF_MissionBriefingAttributes for briefings
Per Group:
TMF_assignGear_faction for assigned loadouts (optional)

**Comment by BorderKeeper** [comment]
Parser done

**Comment by Freddo3000** [comment]
Link commit?
